config/routes.rb
Rails.application.routes.draw do
  
   root 'static_pages#home'

  get 'about'      =>  'static_pages#about'

  get 'academic'   =>  'static_pages#academic'

  get 'admision'   =>  'static_pages#admision'

  get 'contacts'   =>  'static_pages#contacts'

  get 'news'       =>  'static_pages#news'

  get 'structure'  =>  'static_pages#structure'

  get 'pdf'        =>  'download#pdf'

  get 'pdf2'        => 'download#pdf2'

  get 'doc'        =>  'download#doc'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/download_controller.rb
class DownloadController < ApplicationController
 
 def pdf
    send_file Rails.root.join('data', 'results.pdf'), :type=>"application/pdf", :x_sendfile=>true
  end

  def pdf2
    send_file Rails.root.join('data', 'fee-structure.pdf'), :type=>"application/pdf", :x_sendfile=>true
  end

  def doc
    send_file Rails.root.join('data', 'application-form.docx'), :type=>"application/doc", :x_sendfile=>true
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def academic
  end

  def admision
  end

  def contacts
  end

  def news
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/download_helper.rb
module DownloadHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/download/doc.html.erb
<h1>Download#doc</h1>
<p>Find me in app/views/download/doc.html.erb</p>

app/views/download/index.html.erb
<h1>Download#index</h1>
<p>Find me in app/views/download/index.html.erb</p>

app/views/download/pdf.html.erb
<h1>Download#pdf</h1>
<p>Find me in app/views/download/pdf.html.erb</p>

app/views/layouts/_carouselslider.html.erb
<div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
      <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>
    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">

      <div class="item active">
        <%= image_tag("pax-logo-2.png", :alt => "School moto", :class=>"image") %>
        <div class="carousel-caption">
          <h3>head</h3>
          <p>description</p>
        </div>
      </div>

      <div class="item">
        <%= image_tag("pax-logo-2.png", :alt => "School moto", :class=>"image") %>
        <div class="carousel-caption">
          <h3>head</h3>
          <p>description</p>
        </div>
      </div>
    
      <div class="item">
        <%= image_tag("pax-logo-2.png", :alt => "School moto", :class=>"image") %>
        <div class="carousel-caption">
          <h3>head</h3>
          <p>Description</p>
        </div>
      </div>

      <div class="item">
        <%= image_tag("pax-logo-2.png", :alt => "School moto", :class=>"image") %>
        <div class="carousel-caption">
          <h3>head</h3>
          <p>Description</p>
        </div>
      </div>
  
    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Pax english medium school © 2016
  </small>
  <nav>
    <ul>
      <li><a href="http://www.maitco.co.tz" target="blank">Designer</a></li>
      <li> | </li>
      <li><%= link_to "Location and Direction", '#' %></li>
    </ul>
    <div class="fb-like" data-href="https://facebook.com/maitco" data-layout="standard" data-action="like"       data-show-faces="true" data-share="true">
    </div>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed navbar-inverse">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav">
        <li><%= link_to "Home", root_path %></li>
        <li><p>|</p></li>
        <li><%= link_to "Admision", admision_path %></li>
        <li><p>|</p></li>
        <li><%= link_to "Academic", academic_path %></li>
        <li><p>|</p></li>
        <li><%= link_to "Contact Us", contacts_path %></li>
        <li><p>|</p></li>
        <li><%= link_to "News & Events", news_path %></li>
        <li><p>|</p></li>
        <li><%= link_to "About Us", about_path %></li>
      </ul>

      <div class="social-icon">
         <a href="http://twitter.com/minimalmonkey" class="icon-button twitter"><i class="icon-twitter"></i><span></span></a>
        <a href="http://facebook.com" class="icon-button facebook"><i class="icon-facebook"></i><span></span></a>
        <a href="http://plus.google.com" class="icon-button google-plus"><i class="icon-google-plus"></i><span></span></a>
      </div>
    </nav>
  </div>
</header>

app/views/layouts/_sidebar.html.erb
<div class="sidebar">
  	<ul class="notice">
  	  <h4>Notice board</h4>
  		<li>Parent meeting.</li>
  		<li>School board meeting</li>
  		<li>First sermister examination</li>
  		<li>Changes in school timetable</li>
  	</ul>
  	<ul class="downloads">
  		<h4>Quick downloads link</h4>
  		<li>Admission form 2016</li>
  		<li>Fee structure</li>
  		<li>School rules</li>
  	</ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pax</title>
  <link rel="stylesheet" type="text/css" href="http://www.w3schools.com/lib/w3.css">
  <link rel='stylesheet prefetch' href='http://netdna.bootstrapcdn.com/font-awesome/3.1.1/css/font-awesome.css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
	
  <%= csrf_meta_tags %>
 
</head>
<body>
  <div class="container">
   <img>
    <%= image_tag("pax-web-banner.png", :alt => "logo", :class=>"banner") %>
   </img>
   
   <%= render 'layouts/header' %>

   <%= yield %>

  </div>
  
  <%= render 'layouts/footer' %>
</body>
</html>

app/views/static_pages/about.html.erb
<div class="container">
	<h2>About PAX</h2>
	<p>Pax English Medium Primary School is the education institute that provide nursery and primary level education</p>
	<p>Pax English Medium School was founded in 2015 and oficial registered in 2016 with registration number ..... and national examination are facilitated</p>
	<p>Our teacher provide execelent education and are choosen if they show good records. The teaching language is English. There are few teachers from outside the country who enrich school with their education skills.</p>
	<p>Class level start from pre-school to the highetst level standard seven</p>

	<h2>Location and direction</h2>
	<p>Pax english medium school is located at Mji mwema, kigamboni, Dar es salaam. Few meters from oilcom-mjimwema  petrol station. It is located 10 kilometer from kivukoni ferry</p>


<%= render 'layouts/sidebar' %>
</div>

app/views/static_pages/academic.html.erb
<div class="container">
  <h2>Academic program</h2>
  <p>Our school provide education to various level, so far we have...</p>
    <ul>
    	<li>Nursery level</li>
    	<li>Primary</li>
    </ul>

  <div class="row">
    <div class="col-sm">
        <h2>Academic Results</h2>
    	<p>You can download and view all previously result of each sermister</p>
    </div>
    <div class="col-sm-4">
	   <h3>Results 2016</h3>
	     <ul>
	     	<li><%= link_to "results_first_sermister_class_1", pdf_path %></li>
	     	<li><%= link_to "results_first_sermister_class_2", pdf_path %></li>
	     	<li><%= link_to "results_first_sermister_class_3", pdf_path %></li>
	     	<li><%= link_to "results_first_sermister_class_4", pdf_path %></li>
	     </ul>
	</div>
	<div class="col-sm-4">
	   <h3>Results 2015</h3>
	     <ul>
	     	<li><%= link_to "results_first_sermister_class_1", pdf_path %></li>
	     	<li><%= link_to "results_first_sermister_class_2", pdf_path %></li>
	     	<li><%= link_to "results_first_sermister_class_3", pdf_path %></li>
	     	<li><%= link_to "results_first_sermister_class_4", pdf_path %></li>
	     </ul>
	</div>
	<div class="col-sm-4">
	   <h3>Results 2015</h3>
	     <ul>
	     	<li><%= link_to "results_first_sermister_class_1", pdf_path %></li>
	     	<li><%= link_to "results_first_sermister_class_2", pdf_path %></li>
	     	<li><%= link_to "results_first_sermister_class_3", pdf_path %></li>
	     	<li><%= link_to "results_first_sermister_class_4", pdf_path %></li>
	     </ul>
	</div>
  </div>
	
	<%= render 'layouts/sidebar' %>
</div>

app/views/static_pages/admision.html.erb
<div class="container">
	<div class="">
		<h2>Admisions</h2>
		<p>There are several key entry point to PAX ENGLISH MEDIUM SCHOOL.</p>
		<ul>
			<li>Student must have atleast 5 years old</li>
			<li>Student must be mental fit</li>
			<li>We accept student from any school</li>
		</ul>
	</div>
	<div class="">
	    <h2>Application</h2>
	    <p>All aplication is done through head teacher or School Director </br> You can download application form <%= link_to "here", doc_path %></p>
	</div>
	<div class="">
		<h2>Fee structure</h2>
		<p>Click <%= link_to "here", pdf2_path %> to download fee structure of our school</p>
	</div>

	<%= render 'layouts/sidebar' %>
</div>

app/views/static_pages/contacts.html.erb
<div class="container">
	<h2>Contact us through:-</h2>
	<table class="contacts">
	   <tr>
	   	  <th>Name</th>
	   	  <th>Position</th>
	   	  <th>Contacts</th>
	   </tr>
	   <tr>
	   	  <td>Mary Herman Sampala</td>
	   	  <td>School Director</td>
	   	  <td>0658923513</td>
	   </tr>
	   <tr>
	   	  <td>Malaika Kimomwe</td>
	   	  <td>Ass. Head teacher</td>
	   	  <td>0655978641</td>
	   </tr>
	   <tr>
	   	  <td>Malaika Kimomwe</td>
	   	  <td>Academi teacher</td>
	   	  <td>0655978641</td>
	   </tr>
		
	</table>

	<h2>Campus</h2>
	<p>Pax English Medium primary school</br>P.o.box 38068</br>Mji mwema, Kigamboni</br>Dar es salaam</p>

	<%= render 'layouts/sidebar' %>
</div>

app/views/static_pages/home.html.erb
<%= render 'layouts/carouselslider' %>
<div class="w3-container">

	<table class="table1">
	 <tr>
	  <th>Who are we?</th>
	  <th>Mission</th>
	 </tr>
	 <tr>
		<td>
		Pax English medium schools is the school that based on providing education service ruther than doing business. Our school offer nussery education and primary school education. It is located at mji mwema kigamboni Dar es salam few kilometer from kivukoni fery. Our aim is to provide maximum effort for you children's future education life <%= link_to "read more", about_path %>
		</td>	  
		<td>
		  Our mission is blah blah blha abjkakjakhak ajjkhahkjha ajajkajhkah ajhkahkakhakha ajjaj
		  Our  mission is bla b;la hbla b;la bajhakajjhyja khakha hjhasjnkasua kashkhakkha
		</td>
	 </tr>
	 <tr>
	  <th>Vission</th>
	  <th>Objectives</th>
	 </tr>
	 <tr>
		<td>
		  Our mission is blah blah blha abjkakjakhak ajjkhahkjha ajajkajhkah ajhkahkakhakha ajjaj
		  Our  mission is bla b;la hbla b;la bajhakajjhyja khakha hjhasjnkasua kashkhakkha
		  Our mission is blah blah blha abjkakjakhak ajjkhahkjha ajajkajhkah ajhkahkakhakha ajjaj
		</td>	  
		<td>
		  Our mission is blah blah blha abjkakjakhak ajjkhahkjha ajajkajhkah ajhkahkakhakha ajjaj
		  Our  mission is bla b;la hbla b;la bajhakajjhyja khakha hjhasjnkasua kashkhakkha
		</td>
	 </tr>
	</table>

	<%= render 'layouts/sidebar' %>
</div>

app/views/static_pages/news.html.erb
<div class="container">
	<h2>News and Events</h2>
	<p><em>21/01/2016</em> | <a href="#">Admission 2016</a></p>
	<p><em>01/01/2016</em> | <a href="#">Anouncement for parents meeting</a></p>
	<p><em>12/12/2015</em> | <a href="#">End of second sermister ceremon</a></p>

	<%= render 'layouts/sidebar' %>
</div>